#---------------------------

CC=g++
CFLAGS=

#---------------------------

.PHONY: all clean

all: list map set vector

list:
	$(CC) -o listTest listTest.cpp
map:
	$(CC) -o mapTest mapTest.cpp
set:
	$(CC) -o setTest setTest.cpp
vector:
	$(CC) -o vectorTest vectorTest.cpp

#------------
clean:
	rm -rf listTest mapTest setTest vectorTest
